# Generated by Django 3.2.5 on 2021-07-24 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_name', models.CharField(max_length=200)),
                ('subcat_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.category')),
            ],
            options={
                'verbose_name': 'sub-category',
                'verbose_name_plural': 'sub-categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.TextField()),
                ('product_img', models.ImageField(default='', upload_to='mall/images')),
                ('product_mrp', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_pub_time', models.DateField()),
                ('product_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mall.category')),
                ('product_subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mall.subcategory')),
            ],
        ),
    ]
