# Generated by Django 3.2.5 on 2021-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20210731_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_products', models.CharField(max_length=500)),
                ('order_full_name', models.CharField(max_length=80)),
                ('order_mobile', models.CharField(max_length=14)),
                ('order_address', models.CharField(max_length=100)),
                ('order_city', models.CharField(max_length=50)),
                ('order_state', models.CharField(max_length=50)),
                ('order_pincode', models.IntegerField()),
                ('order_prod_quantity', models.IntegerField()),
            ],
        ),
    ]
