# Generated by Django 3.2.5 on 2021-08-07 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.product'),
        ),
    ]
