# Generated by Django 3.2.5 on 2021-08-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_pincode',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_prod_quantity',
            new_name='prod_quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_full_name',
            new_name='user_name',
        ),
    ]
