# Generated by Django 3.2.5 on 2021-08-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0010_order_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Payment Success', 'Payment Success'), ('Payment Failed', 'Payment Failed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Refunded', 'Refunded')], default='Requested', max_length=256),
        ),
    ]
