# Generated by Django 3.2.5 on 2021-08-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0011_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
