# Generated by Django 3.2.5 on 2021-08-24 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0013_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
