# Generated by Django 3.2.5 on 2021-08-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0014_order_ordertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pub_time',
            field=models.DateTimeField(),
        ),
    ]
